openapi: 3.0.0
info:
  title: job-api
  version: 1.0.0
servers:
  - url: https://job-api-ctrs.onrender.com/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      tags:
        - default
      summary: register-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: anna
                email: anna8@gmail.com
                password: anna88888
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - default
      summary: login-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: maribabs8@gmail.com
                password: maribabs
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs:
    post:
      tags:
        - default
      summary: create-job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: mari
                company: wema-bank
                position: backend-developer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: all jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - default
      summary: one-job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - default
      summary: update-job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: Twitter
                position: fullstackdeveloper
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: one-job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}